version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /NoteApp-0.0.1.jar
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: deploy-app.sh
      timeout: 300
      runas: root

